In [55]:
import numpy as np

In [56]:
# Q1

a = np.array([0,1,2,3,4,5])
print(a)
print(type(a))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [57]:
# Q2

arr = np.array([2.4,5.6])

if arr.dtype == np.float64:
    print("yes")

else:
    print("no")


yes


In [58]:
# Q3

complexx = np.array([1+2j, 3+6j],dtype=np.complex128)
complexx

array([1.+2.j, 3.+6.j])

In [59]:
# Q4


arra = np.array([1,2,3],dtype=int)
arra

float_array = arra.astype(float)
print(float_array.dtype)

float64


In [60]:
# Q5

array = np.array([1.2,3.4],dtype=np.float64)

convert = array.astype(np.float32)
print(convert.dtype)



float32


In [61]:
#Q 6

def array_attributes(array):
    shape = array.shape
    size = array.size
    datatype = array.dtype
    return shape , size , datatype


array = np.array([[1,2],[4,5]])
shape , size , datatype  = array_attributes(array)

print("shape:",shape)
print("size:" , size)
print("datatype:",datatype)

shape: (2, 2)
size: 4
datatype: int32


In [62]:
# Q 7

def array_dimension(array):
    dimension = array.ndim
    return dimension


array = np.array([2,4,7])
dimension = array_dimension(array)
print("dimension:",dimension)

dimension: 1


In [63]:
# Q 8

import numpy as np

def item_size_info(array):
    item_size = array.itemsize    
    total_size = array.nbytes     
    return item_size, total_size

arr = np.array([[10, 20], [30, 40]], dtype=np.int32)

item_size, total_size = item_size_info(arr)

print("Item size (bytes):", item_size)
print("Total size (bytes):", total_size)


Item size (bytes): 4
Total size (bytes): 16


In [64]:
import numpy as np

In [65]:
# Q 9

def array_strides(array):
    return array.strides

array = np.array([[1,2],[4,5]])
print(array_strides(array))

(8, 4)


In [66]:
# 10
def shape_strides_relationship(array):
    shape = array.shape
    strides =  array.strides
    return shape , strides

array = np.array([[1,2],[3,4]])
print(shape_strides_relationship(array))
    

((2, 2), (8, 4))


# Array Creation

In [67]:
# Q 11

def create_zeros_array(n):
    zero = np.zeros(n)
    return zero
n = (2,6)
print(create_zeros_array(n))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [68]:
# Q 12

def create_ones_matrix(num):
    ones = np.ones(num)
    return ones

num = ((2,3))
print(create_ones_matrix(num))

[[1. 1. 1.]
 [1. 1. 1.]]


In [69]:
# Q13
def create_range_array(arr):
    array = np.arange(*arr)
    return array

arr = (1,10,2)
print(create_range_array(arr))

[1 3 5 7 9]


In [70]:
# Q14

def generate_linear_space(num):
    line = np.linspace(*num)
    return line

num = (1,10,5)
print(generate_linear_space(num))

[ 1.    3.25  5.5   7.75 10.  ]


In [71]:
# Q15

def create_identity_array(num):
    eye = np.eye(*num)
    return eye

num = (3,3)
print(create_identity_array(num))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [72]:
# Q16
 
def python_to_array(list1):
    arr = np.array(list1)
    return arr

list1 = [1,2,3,4,5,6]
print(python_to_array(list1))

[1 2 3 4 5 6]


In [73]:
#Q17
def new_view(arr):
    view = arr.view()
    return view

arr = np.array([1,2])
print(new_view(arr))

[1 2]


In [74]:
# Q18

def concatenate_two_array(num):
    concatenate = np.concatenate(*num)
    return concatenate

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

num = ((a,b),1)

print(concatenate_two_array(num))

[[1 2 5 6]
 [3 4 7 8]]


In [75]:
# Q 19

def diff_array(num):
    diff = np.concatenate(*num)
    return diff

a = np.array([[1,2],[4,5]])
b = np.array([[3],[7]])
num = ((a,b),1)
print(diff_array(num))

[[1 2 3]
 [4 5 7]]


In [76]:
# Q 20

def vertical_stack(num):
    stack = np.vstack(num)
    return stack

a = np.arange(12).reshape(3,4)
b = np.arange(24).reshape(6,4)

num = ((a,b))
print(vertical_stack(num))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# Array Generation

In [77]:
# Q 21

def generate_array(num):
    arr = np.arange(*num)
    return arr

num = (1,11,1)
print(generate_array(num))

[ 1  2  3  4  5  6  7  8  9 10]


In [78]:
# q22

def generate_equal_space(num):
    equal = np.linspace(*num)
    return equal

num = (0,1,10)
print(generate_equal_space(num))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [79]:
# Q 23

def generate_logspace(num):
    logspace = np.logspace(*num)
    return logspace

num = (0 , 3,5)
print(generate_logspace(num))

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [80]:
# Q26

arr = np.array([1,2,3,4,5])
print(arr[2])



3


In [81]:
# Q27

arr = np.arange(12).reshape(3,4)
print(arr)
print(arr[1,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6


In [82]:
# Q28

a1 = np.arange(12).reshape(3,4)
print(a1[a1>5])

[ 6  7  8  9 10 11]


In [83]:
# Q29

a2 = np.array([1,2,3,4,5,6,7])
print(a2[2:5])

[3 4 5]


In [84]:
# 30

a2 = np.array([[1,2,3],
              [4,5,6],
               [7,8,9]])

a2[0:2,1:3]




array([[2, 3],
       [5, 6]])

In [85]:
# Q 31
a2 = np.array([[1,2,3],
              [4,5,6],
               [7,8,9]])

a2[0:2,1:3]



array([[2, 3],
       [5, 6]])

In [86]:
# Q 32

a2 = np.array([12,65,45,23,65,14,7])
threshold = sum(a2)/len(a2)

element_greater_than_threshold = a2[a2>threshold]
print(element_greater_than_threshold)

[65 45 65]


In [87]:
# Q 33

a3 = np.arange(27).reshape(3,3,3)

a3[[0,2],2]

array([[ 6,  7,  8],
       [24, 25, 26]])

In [88]:
# Q 34

a1 = np.array([1,2,3,4,6,7,8,9])
print(a1[(a1%2==0) & (a1>5)])

[6 8]


In [89]:
# Q35

a1 = np.array([[1,2,3,4,6,7,8,9]])
print(a1[0,6])


8


In [90]:
# Q 36

a = np.array([[1,2,3],
              [4,5,6]])

result = a+ 5    # this is called broadcasting
print(result)

[[ 6  7  8]
 [ 9 10 11]]


# Aggregations and Statistics 

In [91]:
# Q41
a = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
mean = np.mean(a,0)
print(mean)

[4. 5. 6.]


In [92]:
# Q42
a = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

maxi = np.max(a , axis=1)
maxi

array([3, 6, 9])

In [93]:
# Q43

a = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

indmax = np.argmax(a , axis=0)
indmax

array([2, 2, 2], dtype=int64)

# reshape and flattening


In [94]:
# Q46

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
# Q47

for i in np.nditer(a):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11


In [96]:
# Q 48

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.concatenate((a,b),0)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
# Q 49

a1 = np.arange(12).reshape(3,4)
np.hsplit(a1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [98]:
# Q 50

a = [1,2,3,4,5,6,7]
remove = a.pop(2)
remove

insert = a.insert(0,2)
insert
a

[2, 1, 2, 4, 5, 6, 7]

In [99]:
# Q51

a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
result = a1+a2
print(result)

[ 6  8 10 12]


In [100]:
# q52

a1 = np.array([5,3,4])
a2 = np.array([1,2,3])
result = a1 - a2
print(result)

[4 1 1]


In [101]:
# Q 53
a1 = np.array([5,3,4])
a2 = np.array([1,2,3])

result = a1 * a2
print(result)

[ 5  6 12]


In [102]:
# Q54
a1 = np.array([5,3,4])
a2 = np.array([1,2,3])

result = (a1 / a2)
print(result)

[5.         1.5        1.33333333]


In [103]:
# Q 55

a1 = np.array([5,3,4])
a2 = np.array([1,2,3])

result = (a1 ** a2)
print(result)

[ 5  9 64]


# String Operations 

In [104]:
# Q 56
string_array = np.array(["apple","banana","cat","dog"])

substring  = "apple"

count = np.char.count(string_array,substring)
print(count)

[1 0 0 0]


In [105]:
# q 57


arr = np.array(["Hello", "WORLD", "gOoD", "MorninG"])

uppercase_chars = [char for word in arr for char in word if char.isupper()]

print(uppercase_chars)


['H', 'W', 'O', 'R', 'L', 'D', 'O', 'D', 'M', 'G']


In [106]:
# Q 58

arr = np.array(["hello","hi","how"])

replace = np.char.replace(arr,"hello","why")
print(replace)

['why' 'hi' 'how']


In [107]:
# q 59

arr = np.array(["hello","ho","why"])
arr1 = np.array(["jat","jai","raj"])
print(np.char.add(arr,arr1))

['hellojat' 'hojai' 'whyraj']


In [108]:
# q 60


arr = np.array(["Hello", "Good Morning", "NumPy", "AI"])

lengths = np.char.str_len(arr)

max_length = np.max(lengths)

print("Length of the longest string:", max_length)


Length of the longest string: 12


In [109]:
# q 61

data = np.random.randint(1, 1001, size=100)

mean_val = np.mean(data)
median_val = np.median(data)
variance_val = np.var(data)
std_deviation = np.std(data)

print("Data:", data)
print("Mean:", mean_val)
print("Median:", median_val)
print("Variance:", variance_val)
print("Standard Deviation:", std_deviation)


Data: [782 927 506 581 512 257 438 805 603 504 513 882 964 852 852 131 670 410
 729  87 697 867 769 794  65 663 481 778 962 969 521 255  63 617 176 914
 937 252 471  17 758 459 353 732   4 119 961 353 325 849 597 637 116 377
 620 235 529 308 266 815 336 995 175 663 864 749 825 550 547  20 690  99
 212 570 930 204 536 687 237  45 991 454 755 568 177 784  20  48 258 755
 311 724 933 830 336 543 362  31 719 528]
Mean: 527.47
Median: 545.0
Variance: 84047.3891
Standard Deviation: 289.9092773610393


In [110]:
# q62

data = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print("Data:", data)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Data: [88 62 86 92 99 85 21  3 78 78 85 69 25 99 14 67 58 19 49 59 71 52 24 50
 69 87 61  7 61 30 80 48 80 75 54 78 98 15 89 80 90 85 77 59 51 77 30 80
 74 45]
25th Percentile: 49.25
75th Percentile: 80.0


In [111]:
# q 63

a = np.array([10, 20, 30, 40, 50])
b = np.array([15, 25, 35, 45, 55])

corr_matrix = np.corrcoef(a, b)

corr_coef = corr_matrix[0, 1]

print("Correlation coefficient matrix:\n", corr_matrix)
print("Correlation coefficient:", corr_coef)


Correlation coefficient matrix:
 [[1. 1.]
 [1. 1.]]
Correlation coefficient: 1.0


In [112]:
# Q 64

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

result = np.dot(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Result of A dot B:\n", result)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Result of A dot B:
 [[19 22]
 [43 50]]


In [113]:
# Q 65

data = np.random.randint(1, 101, size=50)

p10 = np.percentile(data, 10)
p50 = np.percentile(data, 50) 
p90 = np.percentile(data, 90)

q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)

print("Data:", data)
print("10th Percentile:", p10)
print("50th Percentile (Median):", p50)
print("90th Percentile:", p90)
print("Q1 (25th Percentile):", q1)
print("Q3 (75th Percentile):", q3)


Data: [ 38  85  20  62  42  77  40  16  17  79  85  66  97  72  43  26  64  87
  10  83  47  49  75  70   3   9  64  40  43  49  91  66  20  65  40  58
  89  40  94  34  93  10  61  84   4  65 100  74  63  61]
10th Percentile: 15.400000000000002
50th Percentile (Median): 61.5
90th Percentile: 89.2
Q1 (25th Percentile): 40.0
Q3 (75th Percentile): 76.5


In [114]:
# Q 66
arr = np.array([10, 25, 30, 40, 25, 50])

indices = np.where(arr == 25)

print("Indices of 25:", indices[0])


Indices of 25: [1 4]


In [115]:
# Q67

random_array = np.random.randint(1, 101, size=10)
sorted_array = np.sort(random_array)

print("Original array:", random_array)
print("Sorted array:", sorted_array)


Original array: [ 49  12  70  56  95  78  62  37  39 100]
Sorted array: [ 12  37  39  49  56  62  70  78  95 100]


In [116]:
# Q68

arr = np.array([5, 18, 25, 33, 12, 45])

filtered = arr[arr > 20]
print("Elements > 20:", filtered)


Elements > 20: [25 33 45]


In [117]:
# Q 69

arr = np.array([9, 15, 20, 22, 30, 41])

filtered = arr[arr % 3 == 0]
print("Elements divisible by 3:", filtered)


Elements divisible by 3: [ 9 15 30]


In [118]:
# Q 70

arr = np.array([10, 21, 25, 35, 40, 50])

filtered = arr[(arr >= 20) & (arr <= 40)]
print("Elements between 20 and 40:", filtered)


Elements between 20 and 40: [21 25 35 40]


In [119]:
# Q71

arr = np.array([1, 2, 3], dtype=np.int32)

print("Byte order:", arr.dtype.byteorder)


Byte order: =


In [120]:
# Q 72

print("Original array:", arr)

arr.byteswap(inplace=True)

print("After byte swap:", arr)


Original array: [1 2 3]
After byte swap: [16777216 33554432 50331648]
